name: Node.js Package

on:
  push: null
  schedule:
    - cron: 0 5 1-31/2 * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm config set registry https://npm.pkg.github.com/patternsandbox
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.WORKFLOW_PACKAGE_TOKEN }}" > ~/.npmrc
      - run: npm ci
      - run: npm update
      - run: npm test
      - run: npm run build:readme
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
